name: Continuous Deployment Pipeline

on:
  workflow_run:
    workflows: ["Continuous Integration Pipeline"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Deploy to Oracle VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "Start Deploying EC2..."
            cd /home/ubuntu
            sudo bash -c 'echo "IMAGE_TAG=${{github.event.workflow_run.head_sha}}" > .env'
            sudo docker compose pull backend-service
            sudo docker compose up -d --force-recreate backend-service
            sudo docker image prune -f
            echo "Deployment EC2 Successfully!"